# These are supported funding model platforms
# Uncomment and fill in the appropriate fields when ready

# github: [username]
# open_collective: jninty
# ko_fi: # Replace with a single Ko-fi username
# custom: ["https://example.com/sponsor"]
