import { addDays, formatISO, parseISO } from "date-fns";
import type { TaskRule } from "../validation/taskRule.schema.ts";
import type { PlantInstance } from "../validation/plantInstance.schema.ts";
import type { Settings } from "../validation/settings.schema.ts";
import type { ActivityType } from "../validation/journalEntry.schema.ts";
import type { TaskPriority } from "../validation/task.schema.ts";

export interface TaskSuggestion {
  title: string;
  dueDate: string;
  priority: TaskPriority;
  activityType?: ActivityType;
  plantInstanceId: string;
  ruleId: string;
  isAutoGenerated: true;
}

/**
 * Check whether a rule's appliesTo criteria match a plant.
 * All specified criteria must match (AND logic).
 * tagsAny uses OR logic within the array.
 * Plants with status "removed" or "dead" are skipped.
 */
export function matchesPlant(rule: TaskRule, plant: PlantInstance): boolean {
  if (plant.status === "removed" || plant.status === "dead") return false;

  const { appliesTo } = rule;

  if (appliesTo.plantType != null && appliesTo.plantType !== plant.type) {
    return false;
  }

  if (appliesTo.species != null && appliesTo.species !== plant.species) {
    return false;
  }

  if (appliesTo.tagsAny != null) {
    const hasMatch = appliesTo.tagsAny.some((tag) => plant.tags.includes(tag));
    if (!hasMatch) return false;
  }

  return true;
}

/**
 * Compute the ISO date (YYYY-MM-DD) when a rule's trigger fires.
 * Returns undefined if required fields are missing.
 */
export function computeTriggerDate(
  rule: TaskRule,
  settings: Pick<Settings, "lastFrostDate" | "firstFrostDate">,
  year?: number,
): string | undefined {
  const { trigger } = rule;

  switch (trigger.type) {
    case "relative_to_last_frost": {
      if (trigger.offsetDays == null) return undefined;
      const base = parseISO(settings.lastFrostDate);
      return formatISO(addDays(base, trigger.offsetDays), {
        representation: "date",
      });
    }
    case "relative_to_first_frost": {
      if (trigger.offsetDays == null) return undefined;
      const base = parseISO(settings.firstFrostDate);
      return formatISO(addDays(base, trigger.offsetDays), {
        representation: "date",
      });
    }
    case "seasonal": {
      if (trigger.month == null) return undefined;
      const y = year ?? new Date().getFullYear();
      const m = String(trigger.month).padStart(2, "0");
      const d =
        trigger.day != null
          ? String(trigger.day).padStart(2, "0")
          : "01";
      return `${String(y)}-${m}-${d}`;
    }
    case "fixed_date": {
      if (trigger.month == null) return undefined;
      const y = year ?? new Date().getFullYear();
      const m = String(trigger.month).padStart(2, "0");
      const d =
        trigger.day != null
          ? String(trigger.day).padStart(2, "0")
          : "01";
      return `${String(y)}-${m}-${d}`;
    }
  }
}

/**
 * Generate task suggestions by evaluating all rules against all plants.
 * `existingKeys` is a Set of "ruleId::plantInstanceId" strings for deduplication.
 * `today` is an ISO date string (YYYY-MM-DD).
 */
export function generateSuggestions(
  rules: TaskRule[],
  plants: PlantInstance[],
  settings: Pick<Settings, "lastFrostDate" | "firstFrostDate">,
  today: string,
  existingKeys?: Set<string>,
): TaskSuggestion[] {
  const suggestions: TaskSuggestion[] = [];
  const year = parseInt(today.slice(0, 4), 10);

  for (const rule of rules) {
    const triggerDate = computeTriggerDate(rule, settings, year);
    if (triggerDate == null || triggerDate > today) continue;

    for (const plant of plants) {
      if (!matchesPlant(rule, plant)) continue;

      const key = `${rule.id}::${plant.id}`;
      if (existingKeys?.has(key)) continue;

      suggestions.push({
        title: rule.task.title,
        dueDate: triggerDate,
        priority: rule.task.defaultPriority ?? "normal",
        ...(rule.task.activityType != null
          ? { activityType: rule.task.activityType }
          : {}),
        plantInstanceId: plant.id,
        ruleId: rule.id,
        isAutoGenerated: true,
      });
    }
  }

  return suggestions;
}
