import { Hono } from "hono";
import { and, eq, inArray, isNull, sql } from "drizzle-orm";
import { db } from "../db/client.ts";
import { plantReminders, tasks } from "../db/schema.ts";
import { requireAuth } from "../middleware/requireAuth.ts";
import type { AppVariables } from "../types.ts";

const router = new Hono<{ Variables: AppVariables }>();

function now(): string {
  return new Date().toISOString();
}

function todayDate(): string {
  return new Date().toISOString().slice(0, 10);
}

// ─── Date helpers ─────────────────────────────────────────────────────────────

/**
 * Round a date string to the nearest 1st or 15th of a month.
 * day 1–7   → 1st of same month
 * day 8–22  → 15th of same month
 * day 23–31 → 1st of next month
 */
export function roundToFirstOrFifteenth(dateStr: string): string {
  const parts = dateStr.split("-").map(Number);
  const year = parts[0] ?? 2024;
  const month = parts[1] ?? 1;
  const day = parts[2] ?? 1;

  if (day <= 7) {
    return `${year}-${String(month).padStart(2, "0")}-01`;
  }
  if (day <= 22) {
    return `${year}-${String(month).padStart(2, "0")}-15`;
  }
  // Round to 1st of next month
  const next = new Date(year, month, 1); // month is 0-indexed so this is next month
  return `${next.getFullYear()}-${String(next.getMonth() + 1).padStart(2, "0")}-01`;
}

// ─── Recurrence helpers ───────────────────────────────────────────────────────

const RECURRENCE_MONTHS: Record<string, number> = {
  biannual: 6,
  yearly: 12,
  every_2y: 24,
  every_3y: 36,
  every_4y: 48,
};

function totalMonths(dateStr: string): number {
  const parts = dateStr.split("-").map(Number);
  return (parts[0] ?? 0) * 12 + ((parts[1] ?? 1) - 1);
}

/**
 * Returns true if today is an occurrence date for this reminder,
 * and the reminder hasn't already run today.
 */
export function isOccurrenceToday(
  startDate: string,
  recurrence: string,
  lastRunAt: string | null,
): boolean {
  const today = todayDate();
  if (lastRunAt === today) return false;

  const startDay = parseInt(startDate.slice(8, 10), 10);
  const todayDay = parseInt(today.slice(8, 10), 10);
  if (startDay !== todayDay) return false;

  if (recurrence === "once") {
    return today === startDate;
  }

  const interval = RECURRENCE_MONTHS[recurrence];
  if (!interval) return false;

  const diff = totalMonths(today) - totalMonths(startDate);
  if (diff < 0) return false;
  return diff % interval === 0;
}

// ─── Task helpers ─────────────────────────────────────────────────────────────

async function deleteOpenTasksForReminder(reminderId: string, userId: string) {
  const openTasks = await db
    .select({ id: tasks.id })
    .from(tasks)
    .where(
      and(
        eq(tasks.userId, userId),
        eq(tasks.ruleId, reminderId),
        eq(tasks.isCompleted, false),
        isNull(tasks.deletedAt),
      ),
    );

  if (openTasks.length === 0) return;

  const ts = now();
  await db
    .update(tasks)
    .set({ deletedAt: ts, updatedAt: ts, version: sql`${tasks.version} + 1` })
    .where(
      and(
        eq(tasks.userId, userId),
        inArray(
          tasks.id,
          openTasks.map((t) => t.id),
        ),
      ),
    );
}

type Reminder = typeof plantReminders.$inferSelect;

async function createTaskForReminder(reminder: Reminder) {
  const ts = now();
  const today = todayDate();
  await db.insert(tasks).values({
    id: crypto.randomUUID(),
    userId: reminder.userId,
    version: 1,
    createdAt: ts,
    updatedAt: ts,
    title: reminder.title,
    description: reminder.notes ?? null,
    plantInstanceId: reminder.plantId,
    dueDate: today,
    priority: "normal",
    isCompleted: false,
    isAutoGenerated: true,
    ruleId: reminder.id,
    generatedAt: ts,
    dismissedAt: null,
    recurrence: null,
    seasonId: null,
    bedId: null,
    completedAt: null,
  });

  const nextStatus = reminder.recurrence === "once" ? "expired" : "active";
  await db
    .update(plantReminders)
    .set({ lastRunAt: today, status: nextStatus, updatedAt: ts, version: sql`${plantReminders.version} + 1` })
    .where(eq(plantReminders.id, reminder.id));
}

// ─── Routes ───────────────────────────────────────────────────────────────────

type ReminderBody = {
  plantId: string;
  category: string;
  title: string;
  notes?: string | null;
  startDate: string;
  recurrence: string;
};

/** GET /api/plant-reminders?plantId=xxx */
router.get("/", requireAuth, async (c) => {
  const userId = c.get("userId");
  const plantId = c.req.query("plantId");

  const rows = await db
    .select()
    .from(plantReminders)
    .where(
      and(
        eq(plantReminders.userId, userId),
        isNull(plantReminders.deletedAt),
        ...(plantId ? [eq(plantReminders.plantId, plantId)] : []),
      ),
    );

  return c.json(rows);
});

/** POST /api/plant-reminders — upsert by plantId+category */
router.post("/", requireAuth, async (c) => {
  const userId = c.get("userId");
  const body = await c.req.json<ReminderBody>();
  const roundedDate = roundToFirstOrFifteenth(body.startDate);
  const ts = now();

  // Check if a reminder for this plant+category already exists
  const existing = await db
    .select()
    .from(plantReminders)
    .where(
      and(
        eq(plantReminders.userId, userId),
        eq(plantReminders.plantId, body.plantId),
        eq(plantReminders.category, body.category),
        isNull(plantReminders.deletedAt),
      ),
    )
    .limit(1);

  let reminder: Reminder;

  if (existing[0]) {
    // Update existing — delete its open tasks first
    await deleteOpenTasksForReminder(existing[0].id, userId);

    const result = await db
      .update(plantReminders)
      .set({
        title: body.title,
        notes: body.notes ?? null,
        startDate: roundedDate,
        recurrence: body.recurrence,
        status: "active",
        lastRunAt: null,
        updatedAt: ts,
        version: sql`${plantReminders.version} + 1`,
      })
      .where(eq(plantReminders.id, existing[0].id))
      .returning();
    reminder = result[0]!;
  } else {
    const result = await db
      .insert(plantReminders)
      .values({
        id: crypto.randomUUID(),
        userId,
        plantId: body.plantId,
        category: body.category,
        title: body.title,
        notes: body.notes ?? null,
        startDate: roundedDate,
        recurrence: body.recurrence,
        status: "active",
        lastRunAt: null,
        version: 1,
        createdAt: ts,
        updatedAt: ts,
      })
      .returning();
    reminder = result[0]!;
  }

  // Immediate trigger: if today is an occurrence, create task now
  if (isOccurrenceToday(reminder.startDate, reminder.recurrence, reminder.lastRunAt)) {
    await createTaskForReminder(reminder);
    // Reload to get updated lastRunAt / status
    const updated = await db
      .select()
      .from(plantReminders)
      .where(eq(plantReminders.id, reminder.id))
      .limit(1);
    if (updated[0]) reminder = updated[0];
  }

  return c.json(reminder, 201);
});

/** PATCH /api/plant-reminders/:id */
router.patch("/:id", requireAuth, async (c) => {
  const userId = c.get("userId");
  const id = c.req.param("id") ?? "";
  const body = await c.req.json<Partial<ReminderBody>>();
  const ts = now();

  // Delete open tasks before updating
  await deleteOpenTasksForReminder(id, userId);

  const patch: Record<string, unknown> = { updatedAt: ts, version: sql`${plantReminders.version} + 1` };
  if (body.title !== undefined) patch["title"] = body.title;
  if (body.notes !== undefined) patch["notes"] = body.notes ?? null;
  if (body.startDate !== undefined) patch["startDate"] = roundToFirstOrFifteenth(body.startDate);
  if (body.recurrence !== undefined) patch["recurrence"] = body.recurrence;
  // Reset status and lastRunAt when config changes
  if (body.startDate !== undefined || body.recurrence !== undefined) {
    patch["status"] = "active";
    patch["lastRunAt"] = null;
  }

  const result = await db
    .update(plantReminders)
    .set(patch)
    .where(
      and(
        eq(plantReminders.id, id),
        eq(plantReminders.userId, userId),
        isNull(plantReminders.deletedAt),
      ),
    )
    .returning();

  let reminder = result[0];
  if (!reminder) return c.json({ error: "Not found" }, 404);

  // Immediate trigger check
  if (isOccurrenceToday(reminder.startDate, reminder.recurrence, reminder.lastRunAt)) {
    await createTaskForReminder(reminder);
    const updated = await db
      .select()
      .from(plantReminders)
      .where(eq(plantReminders.id, id))
      .limit(1);
    if (updated[0]) reminder = updated[0];
  }

  return c.json(reminder);
});

/** DELETE /api/plant-reminders/:id */
router.delete("/:id", requireAuth, async (c) => {
  const userId = c.get("userId");
  const id = c.req.param("id") ?? "";

  await deleteOpenTasksForReminder(id, userId);

  const ts = now();
  const result = await db
    .update(plantReminders)
    .set({ deletedAt: ts, updatedAt: ts, version: sql`${plantReminders.version} + 1` })
    .where(
      and(
        eq(plantReminders.id, id),
        eq(plantReminders.userId, userId),
        isNull(plantReminders.deletedAt),
      ),
    )
    .returning();

  if (!result[0]) return c.json({ error: "Not found" }, 404);
  return c.json({ ok: true });
});

export { deleteOpenTasksForReminder, createTaskForReminder };
export default router;
