import { useMemo, useCallback } from "react";
import { useLiveQuery } from "dexie-react-hooks";
import { formatISO, startOfDay } from "date-fns";
import * as taskRuleRepository from "../db/repositories/taskRuleRepository.ts";
import * as plantRepository from "../db/repositories/plantRepository.ts";
import * as taskRepository from "../db/repositories/taskRepository.ts";
import * as seasonRepository from "../db/repositories/seasonRepository.ts";
import { useSettings } from "./useSettings.tsx";
import { useToast } from "../components/ui/Toast.tsx";
import { generateSuggestions, type TaskSuggestion } from "../services/taskEngine.ts";

function todayDate(): string {
  return formatISO(startOfDay(new Date()), { representation: "date" });
}

/**
 * Returns task suggestions from the rule engine, excluding
 * rules that already have a corresponding accepted or dismissed task.
 * Also provides accept/dismiss callbacks.
 */
export function useTaskSuggestions(): {
  suggestions: TaskSuggestion[] | undefined;
  isLoading: boolean;
  acceptSuggestion: (suggestion: TaskSuggestion) => Promise<void>;
  dismissSuggestion: (suggestion: TaskSuggestion) => Promise<void>;
} {
  const { settings } = useSettings();
  const { toast } = useToast();
  const rules = useLiveQuery(() => taskRuleRepository.getAll());
  const plants = useLiveQuery(() => plantRepository.getAll());
  const tasks = useLiveQuery(() => taskRepository.getAll());
  const activeSeason = useLiveQuery(() => seasonRepository.getActive());

  const today = todayDate();

  const suggestions = useMemo(() => {
    if (!rules || !plants || !tasks || !settings) return undefined;

    // Build a set of "ruleId::plantInstanceId" for tasks already generated
    const existingKeys = new Set<string>();
    for (const task of tasks) {
      if (task.ruleId && task.plantInstanceId) {
        existingKeys.add(`${task.ruleId}::${task.plantInstanceId}`);
      }
    }

    return generateSuggestions(rules, plants, settings, today, existingKeys);
  }, [rules, plants, tasks, settings, today]);

  const acceptSuggestion = useCallback(
    async (suggestion: TaskSuggestion) => {
      try {
        await taskRepository.create({
          title: suggestion.title,
          dueDate: suggestion.dueDate,
          priority: suggestion.priority,
          isCompleted: false,
          plantInstanceId: suggestion.plantInstanceId,
          ruleId: suggestion.ruleId,
          isAutoGenerated: true,
          generatedAt: new Date().toISOString(),
          ...(suggestion.activityType != null
            ? { description: `Activity: ${suggestion.activityType}` }
            : {}),
          ...(activeSeason?.id ? { seasonId: activeSeason.id } : {}),
        });
        toast("Task added", "success");
      } catch {
        toast("Failed to add task", "error");
      }
    },
    [activeSeason?.id, toast],
  );

  const dismissSuggestion = useCallback(
    async (suggestion: TaskSuggestion) => {
      try {
        await taskRepository.create({
          title: suggestion.title,
          dueDate: suggestion.dueDate,
          priority: suggestion.priority,
          isCompleted: false,
          plantInstanceId: suggestion.plantInstanceId,
          ruleId: suggestion.ruleId,
          isAutoGenerated: true,
          generatedAt: new Date().toISOString(),
          dismissedAt: new Date().toISOString(),
        });
      } catch {
        toast("Failed to dismiss suggestion", "error");
      }
    },
    [toast],
  );

  return {
    suggestions,
    isLoading: suggestions === undefined,
    acceptSuggestion,
    dismissSuggestion,
  };
}
